apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
  namespace: devops
data:
  DATABASE_URL: "jdbc:mysql://mysql-service:3306/cafedb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
---
apiVersion: v1
kind: Secret
metadata:
  name: spring-secret
  namespace: devops
type: Opaque
data:
  DATABASE_USERNAME: cm9vdA==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tpcafe-app
  namespace: devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tpcafe-app
  template:
    metadata:
      labels:
        app: tpcafe-app
    spec:
      containers:
      - name: tpcafe-app
        image: ghcr.io/imenbouchriha12/tpcafe-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: spring-config
              key: DATABASE_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: spring-secret
              key: DATABASE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: tpcafe-service
  namespace: devops
spec:
  type: NodePort
  ports:
  - port: 8082
    targetPort: 8082
    nodePort: 30082
  selector:
    app: tpcafe-app
